server.port=${SERVER_PORT:9094}
spring.application.name=ms-financiero

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/db_financiero}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Inicialización con datos de prueba (data.sql se ejecuta al arrancar)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.com.grupocordillera.financiero=DEBUG
