server.port=${SERVER_PORT:9092}
spring.application.name=ms-ecommerce

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/db_ecommerce}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase gestiona el esquema — Hibernate solo valida
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.com.grupocordillera.ecommerce=DEBUG
